# Generated by Django 3.2.8 on 2023-04-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='max_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='option',
            name='max_points',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
