# Generated by Django 3.2.8 on 2023-04-09 09:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(max_length=8, unique=True, verbose_name='Цветовой HEX-код тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название вакансии', max_length=200, verbose_name='Название вакансии')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField(help_text='Текстовое описание вакансии', verbose_name='Текст вакансии')),
                ('salary', models.PositiveIntegerField(help_text='Введите размер заработной платы', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Размер заработной платы')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to=settings.AUTH_USER_MODEL, verbose_name='Автор вакансии')),
                ('skills', models.ManyToManyField(related_name='skills', to='vacancy.Skills', verbose_name='Навыки')),
                ('tags', models.ManyToManyField(related_name='vacancy', to='vacancy.Tag', verbose_name='Теги вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='vacancy.vacancy', verbose_name='Избранная вакансия')),
            ],
            options={
                'verbose_name': 'Избранная вакансия',
                'verbose_name_plural': 'Избранные вакансии',
                'ordering': ['author'],
            },
        ),
    ]
