# Generated by Django 3.2.8 on 2023-04-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='image',
        ),
        migrations.CreateModel(
            name='Busyness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип занятости')),
            ],
            options={
                'verbose_name': 'Тип занятости',
                'verbose_name_plural': 'Типы занятости',
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='busyness',
            field=models.ManyToManyField(related_name='vacancy', to='vacancy.Busyness', verbose_name='Тип занятости'),
        ),
    ]
