# Generated by Django 3.2.8 on 2023-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20230410_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='text',
            field=models.TextField(help_text='Текстовое описание вакансии', verbose_name='Описание вакансии'),
        ),
    ]
