# Generated by Django 3.2.8 on 2023-04-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
