# Generated by Django 3.2.8 on 2023-04-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_auto_20230415_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(default=1, help_text='Введите название компании', max_length=200, verbose_name='Название компании'),
            preserve_default=False,
        ),
    ]
