# Generated by Django 3.2.8 on 2023-04-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
    ]
