# Generated by Django 3.2.8 on 2023-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Аутентифицированный пользователь'), ('employer', 'Работодатель')], default='user', max_length=35, verbose_name='Роль'),
        ),
    ]
