# Generated by Django 3.2.8 on 2023-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Соискатель'), ('employer', 'Работодатель')], default='applicant', max_length=35, verbose_name='Роль'),
        ),
    ]
