# Generated by Django 3.2.8 on 2023-04-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_event_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='event_place',
        ),
    ]
